version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  test:
    build: .
    command: [ "npm", "run", "test" ]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=test
